### ISSUE TITLE
Vurdere Ring og meet.jit.si?

### ISSUE THREAD

**Issue by petterreinholdtsen** [sikkertprivatliv/sikkertprivatliv.github.io#4]
Når det gjelder tale og videokonferanse, har du vurdert https://ring.cx/ og https://meet.jit.si/ ?

Alle norske telefonselskaper er i konsesjonen pålagt å tilrettelegge for avlytting av telefonsamtaler, og appear.in eies og drives av Telenor.   Jeg er usikker på hva det gjør med muligheten for avlytting på appear.in, og hvordan en kan kontrollere om det er ende til endekryptering og skjuling av metadata.

**Comment by nechered** [comment]
Hei,
Jit.si ble ikke tatt med siden den hadde blitt fjernet fra privacytools.io, men skal sette dem begge opp til vurdering.  
Når det gjelder kommunikasjonskontroll (avlytting) så får politiet en "speiling" av data i sanntid, uavhengig om det er mobil eller fast bredbånd (så lenge de har kjennelse). Derfor så lenge kommunikasjonen er kryptert så skal det ikke være mulig for politiet å se noe annet enn metadata, Dette gjelder for alle tjenester. Eneste måten å skjule det på å er å være på VPN, men jeg føler det ligger litt over målet for dette prosjektet. Personer som har spesielle trusselbilder (eks journalister eller hjelpearbeidere) bør nok finne mer spesifikk informasjon.

Men skal sjekke mer nøye på begge alternativer senere i uken.

**Comment by nechered** [comment]
@petterreinholdtsen Har sett på jitsi (og testet den både privat og på jobb). meet.jit.si ser ikke ut til å tilby noe mer utover det som appear.in allerede gjør. Kvaliteten var også dårligere i mine test. Men har lagt inn begge som et alternativ i video seksjonen.
